//
// Micropost.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Return all users. */

open class Micropost: Codable {

    /** Micropost ID. */
    public var id: Int
    /** Micropost content. */
    public var content: String
    /** User ID of the micropost. */
    public var userId: Int
    /** Picture info added to the micropost. */
    public var picture: Picture


    
    public init(id: Int, content: String, userId: Int, picture: Picture) {
        self.id = id
        self.content = content
        self.userId = userId
        self.picture = picture
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(content, forKey: "content")
        try container.encode(userId, forKey: "user_id")
        try container.encode(picture, forKey: "picture")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(Int.self, forKey: "id")
        content = try container.decode(String.self, forKey: "content")
        userId = try container.decode(Int.self, forKey: "user_id")
        picture = try container.decode(Picture.self, forKey: "picture")
    }
}

