//
// Picture.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Picture: Codable {

    /** URL of picture.(It will be &#x60;null&#x60; if there are no picture.) */
    public var url: String


    
    public init(url: String) {
        self.url = url
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(url, forKey: "url")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        url = try container.decode(String.self, forKey: "url")
    }
}

